INSERT INTO `civicrm_mailing_bounce_type` (`id`,`name`,`description`,`hold_threshold`)
VALUES
	(1001,'Spam complaint','Spam complaint',1),
	(1002,'Blacklist','Blacklist',1),
	(1003,'ISP block','ISP block',1),
	(1004,'Content block','Content block',1),
	(1005,'URL block','URL block',1),
	(1006,'Excess traffic','Excess traffic',1),
	(1007,'Security violation/virus','Security violation/virus',1),
	(1008,'Open relay','Open relay',1),
	(1009,'Namespace mining detection','Namespace mining detection',1),
	(1010,'Authentication','Authentication',1),
	(1999,'Other','Other',1),
	(2001,'Unknown user','Unknown user',1),
	(2002,'Bad domain','Bad domain',1),
	(2003,'Address error','Address error',1),
	(2004,'Closed account','Closed account',1),
	(2999,'Other','Other',1),
	(3001,'Recipient mailbox full','Recipient mailbox full',0),
	(3002,'Recipient email account is inactive/disabled','Recipient email account is inactive/disabled',1),
	(3003,'Greylist','Address error',1),
	(3999,'Closed account','recipient server continuously asked us to try later',1),
	(4001,'server too busy','Recipients server too busy',0),
	(4002,'data format error','Recipient server returned a data format error',1),
	(4003,'Network error','Network error, non-specific',1),
	(4004,'Too Old','Recipients server rejected message as too old ',1),
	(4006,'configuration error','Recipient network or configuration error , normally a relay denied',1),
	(4999,'Other','Other',1),
	(9999,'Unknown','Unknown',1);